import Head from "next/head";
import { BsFillMoonStarsFill } from "react-icons/bs";
import { AiFillLinkedin, AiFillInstagram, AiFillMail } from "react-icons/ai";
import Image from "next/image";
import deved from "../public/dev-ed-wave.png";
import design from "../public/design.png";
import code from "../public/code.png";
import consulting from "../public/consulting.png";
import web1 from "../public/web1.png";
import web2 from "../public/web2.png";
import web3 from "../public/web3.png";
import web4 from "../public/web4.png";
import web5 from "../public/web5.png";
import web6 from "../public/web6.png";
import { useState } from "react";
import { Zoom, Fade, Rotate } from "react-reveal";

export default function Home() {
  const [darkMode, setDarkMode] = useState(false);
  return (
    <div className={darkMode ? "dark" : ""}>
      <Head>
        <title>Daniel O. Uzoegbu</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="px-10 md:px-20 lg:px-40 dark:bg-gray-800">
        <section className="min-h-screen">
          <Zoom>
            <nav className="py-10 mb-12 flex justify-between">
              <h1 className="text-xl md:text-x font-burtons dark:text-gray-300">
                Daniel O. Uzoegbu
              </h1>
              <ul className="flex items-center">
                <li>
                  <BsFillMoonStarsFill
                    onClick={() => setDarkMode(!darkMode)}
                    className="cursor-pointer text-2xl dark:text-gray-300"
                  />
                </li>
                <li>
                  <a
                    className="bg-gradient-to-r from-cyan-500 to-teal-500 text-white px-4 py-2 rounded-md ml-8"
                    href="https://drive.google.com/file/d/1yBYZ56HWaaSMEOZphbujUTzwngHXei-q/view?usp=share_link"
                  >
                    Resume
                  </a>
                </li>
              </ul>
            </nav>
          </Zoom>
          <div className="text-center p-10">
            <h2 className="text-5xl py-2 text-teal-600 font-medium md:text-6xl sm:text-xl">
              Daniel O. Uzoegbu
            </h2>
            <h3 className="text-2xl py-2 md:text-3xl">
              Developer and Designer.
            </h3>
            <p className="text-md py-5 leading-8 text-gray-500 md:text-xl sm:text-x max-w-lg mx-auto">
              A Freelancer providing services for programming, website
              development, mobile development, app testing, mentoring/tutoring
              and more... Connect with me below, lets get cracking!
            </p>
          </div>
          <Rotate duration={3000} delay={1000} repeat={true}>
            <div className="text-5xl flex justify-center gap-16 py-3 text-gray-800 dark:text-gray-500">
              <AiFillInstagram />
              <AiFillLinkedin />
              <AiFillMail />
            </div>
          </Rotate>
          <div className="relative mx-auto bg-gradient-to-b from-teal-500 rounded-full w-80 h-80 mt-20 overflow-hidden md:h-96 md:w-96">
            <Image src={deved} alt="" layout="fill" objectFit="cover" />
          </div>
        </section>

        <section>
          <div>
            <h3 className="text-3xl py-1 mt-5 font-burtons">
              Services I offer
            </h3>
            <p className="text-md py-2 leading-8 text-gray-800 dark:text-gray-400">
              Since the beginning of my journey as a freelance developer and
              designer, ive done remote works for
              <span className="text-teal-500">
                {" "}
                Personal | startup business, SME, Blogs
              </span>
            </p>
            <p className="text-md py-2 leading-8 text-gray-800 dark:text-gray-400">
              I offer from a wide range of services, including{" "}
              <span className="text-teal-500">
                Brand/logo design, Website development, School management
                system, mentoring and teaching.
              </span>
            </p>
          </div>

          <div className="lg:flex">
            <Fade>
              <div className="flex-1 text-center shadow-lg p-10 rounded-xl my-10">
                <Image src={design} width={100} alt="" height={100} />
                <h3 className="dark:text-gray-400">Beautiful Designs</h3>
                <p>
                  Creating elegant designs suited for your needs following core
                  design theory.
                </p>
              </div>
              <div className="flex-1 text-center shadow-lg p-10 rounded-xl my-10">
                <Image src={code} width={100} alt="" height={100} />
                <h3 className="dark:text-gray-400">Stable software</h3>
                <p>
                  Giving you a stable and modern working application for all
                  platforms.
                </p>
                <ul className="items-center">
                  <li>Javascript | React | Next JS</li>
                  <li>Python Django backend</li>
                  <li>Dart & Flutter</li>
                </ul>
              </div>

              <div className="flex-1 text-center shadow-lg p-10 rounded-xl my-10">
                <Image src={consulting} alt="" width={100} height={100} />
                <h3 className="dark:text-gray-400">Tutoring & Mentoring</h3>
                <p>
                  Starting your journey to software engineering, theres need for
                  mentorship in guiding you through the world of programming.
                </p>
              </div>
            </Fade>
          </div>
          <div className="flex flex-col gap-10 py-10 lg:flex-row lg:flex-wrap justify-center">
            <div className="basis-1/3">
              <Image
                alt=""
                src={web1}
                className="rounded-lg object-cover"
                width={"100%"}
                height={"100%"}
                layout="responsive"
              />
            </div>
            <div className="basis-1/3">
              <Image
                alt=""
                src={web2}
                className="rounded-lg object-cover"
                width={"100%"}
                height={"100%"}
                layout="responsive"
              />
            </div>
            <div className="basis-1/3">
              <Image
                alt=""
                src={web3}
                className="rounded-lg object-cover"
                width={"100%"}
                height={"100%"}
                layout="responsive"
              />
            </div>
            <div className="basis-1/3">
              <Image
                alt=""
                src={web4}
                className="rounded-lg object-cover"
                width={"100%"}
                height={"100%"}
                layout="responsive"
              />
            </div>
            <div className="basis-1/3">
              <Image
                alt=""
                src={web5}
                className="rounded-lg object-cover"
                width={"100%"}
                height={"100%"}
                layout="responsive"
              />
            </div>
            <div className="basis-1/3">
              <Image
                alt=""
                src={web6}
                className="rounded-lg object-cover"
                width={"100%"}
                height={"100%"}
                layout="responsive"
              />
            </div>
          </div>
        </section>
      </main>
    </div>
  );
}
